# Create a security group
- name: Create a volume
  openstack.cloud.volume:
    display_name: '{{ item.vol_name }}'
    availability_zone: "{{ avlblt_zn }}"
    size: '{{ item.vol_size }}'
    state: present
    timeout: 600
  loop: '{{ volumes }}'
  register: os_vol

  #- name: Print return info from the previous task
  #ansible.builtin.debug:
  #var: os_vol

- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.volume.id ] }}'
  loop: '{{ os_vol.results }}'

- ansible.builtin.debug:
    msg: "Volume {{ os_vol_ids }} have been created."
