# Show all available Openstack images
- name: Launch an instance
  openstack.cloud.server:
    auto_ip: false
    availability_zone: "{{ avlblt_zn }}"
    flavor: "{{ instnc_flvr }}"
    image: "{{ instnc_img }}"
    key_name: "{{ instnc_kynm }}"
    name: "{{ item.name }}"
    network: "{{ instnc_ntwrk }}"
    security_groups: "{{ sg_names }}"
    state: present
    timeout: 600
    volumes: "{{ item.volumes }}"
    wait: yes
  loop: "{{ instances }}"
  register: os_instance

  #- name: Print return info from previous task
  #ansible.builtin.debug:
  #  var: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.server.name }} has been created. IP is {{ item['server']['addresses'][instnc_ntwrk][0]['addr'] }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- name: Wait for connection
  ansible.builtin.wait_for:
    host: "{{ item['server']['addresses'][instnc_ntwrk][0]['addr'] }}"
    port: 22
    timeout: 600
    search_regex: OpenSSH
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# Add host to Ansible in-memory inventory
- name: Add host to inventory
  ansible.builtin.add_host:
    name: "{{ item['server']['addresses'][instnc_ntwrk][0]['addr'] }}"
    groups: grp4_groups
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# Create DNS Record Set 
- name: Create DNS Record Set
  openstack.cloud.recordset:
    state: present
    zone: unimelb-comp90024-2023-grp-4.cloud.edu.au.
    name: "{{ item.server.name }}.unimelb-comp90024-2023-grp-4.cloud.edu.au."
    recordset_type: "a"
    records: ["{{ item['server']['addresses'][instnc_ntwrk][0]['addr'] }}"]
    description: RecordSet
    ttl: 3600
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- ansible.builtin.debug:
    msg: "Record set {{ item.server.name }}.unimelb-comp90024-2023-grp-4.cloud.edu.au  has been created. IP is {{ item['server']['addresses'][instnc_ntwrk][0]['addr'] }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined
