- hosts: localhost
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: openstack-security-group
    - role: openstack-volume
    - role: openstack-instance

- hosts: grp4_nodes 
  vars_files:
    - host_vars/vars.yaml
  become: yes
  gather_facts: true

  roles:
    - role: openstack-fs
    - role: docker

- hosts: grp4_db_main, grp4_db_nodes
  vars_files:
    - host_vars/couchdb.yaml
  become: yes

  roles:
    - role: couchdb
    - role: couchdb_setup

- hosts: grp4_db_main
  vars_files:
    - host_vars/couchdb.yaml
  become: yes

  roles:
    - role: couchdb_main

- hosts: grp4_swarm_manager
  become: yes 

  tasks:
    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present

    - name: Get info
      docker_swarm_info:
      register: swarm_info

    - name: Print return info from previous task
      ansible.builtin.debug:
        var: swarm_info

    - name: Set swarm_info as a fact
      set_fact:
        swarm_info: "{{ swarm_info }}"

- hosts: grp4_swarm_workers
  become: yes
  vars_files:
    - host_vars/manager.yaml

  tasks:
    - name: Add nodes to SWARM Manager
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ hostvars[groups['grp4_swarm_manager'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
        remote_addrs: [ "{{ manager }}:2377" ]
